### ISSUE TITLE
Document Installation & Usage

### ISSUE THREAD

**Issue by tomschr** [openSUSE/dapsenv#6]
## Problem

We currently lack a dedicated file with installation & usage instructions.

## Tasks

* [ ] Write installation instructions about this project (probably in an `INSTALL.rst` file), containing:
  * [ ] installation from Python with `setup.py` and a virtual Python environment
  * [ ] installation from/with RPM
* [ ] Write usage instructions
* [ ] Use the RST/Sphinx syntax

Find some inspirations in the original Wiki: https://github.com/mschnitzer/dapsenv/wiki
